### ISSUE TITLE
Web site unavailable.

### ISSUE THREAD

**Issue by everbros** [michal-majer/ui5-b2b-calculator#4]
http://kalkulatorb2b.pl/ seems to be blocked due to missing payments. Is there any other web location?

**Comment by IonBazan** [comment]
@michal-majer I would suggest using https://netlify.com instead - it offers free CDN, static site hosting and SSL certificate.

**Comment by michal-majer** [comment]
@IonBazan Thanks :) 👍  I deployed it on netlify and changed dns :)
